version: "2"
services:
  courtbot:
    build: .
    container_name: courtbot
    env_file:
      - .docker/env
    image: rlucioni/courtbot:latest
    privileged: true
    restart: on-failure
    stdin_open: true
    tty: true
